### ISSUE TITLE
Exception EInOutError: Usb to Serial Adapters unplugging

### ISSUE THREAD

**Issue by sbridger** [TurboPack/AsyncPro#1]
Link to Sourceforge discussion, with a suggested fix:  https://sourceforge.net/p/tpapro/discussion/241883/thread/2f274722/?limit=25#e82c

I think I have seen something similar, and will leave this here to remind myself to the fix.

**Comment by sbridger** [comment]
error fixed now, and realterm adds DeviceChangeNotifier.pas so it can handle usb ports plugged/removed/replaced

Now how to do a pull request from my local branch into here?

**Comment by romankassebaum** [comment]
You should send me a pm. BTW,  The Tokyo version https://github.com/TurboPack-Tokyo/AsyncPro/issues/ is the newest one.

**Comment by sbridger** [comment]
No idea how to send pm's on GH?
My laptop died last year, I think my git has probably gone, but I should get the changes to you, as there were quite a few.

**Comment by romankassebaum** [comment]
I added the method WriteComSafe.
