### ISSUE TITLE
Type Not Allowed Error

### ISSUE THREAD

**Issue by IVCJim** [TurboPack/AsyncPro#1]
I am using C++Builder XE7 Enterprise. I have installed AsyncPro. However, when I put the ApdComPort component on a form to test it I get two "E2109 Type not allowed" errors when I compile the program. The errors are on lines 405 and 410 in the AdPort.hpp file. The lines point to two published properties in the TApdComPort class, "TraceName" and "LogName." I can comment out those two properties in the header file and the program compiles and runs fine but I don't have those two properties anymore. What can I do to fix this?

**Comment by romankassebaum** [comment]
I just fixed the issue.
