### ISSUE TITLE
TapdFaxConverter

### ISSUE THREAD

**Issue by kiwisigi** [TurboPack/AsyncPro#14]
Hi,
I have upgraded from delphi2007 and asyncpro  to Delphi Rio and installed the newest  asyncpro  but cannot get the fax-conversion  from a simple text file to a fax going . It crashes with an access violation  in function:   converter.Converttofile;  (Tapdfaxconverter component).
I put the 12 lines of text into a memo (tstrings) and   memo.lines.SaveToFile(fn,tencoding.ANSI);  -> to make sure the input file is not UTF8 etc. (no special chars are in the text of course, standard font file is in place too..)

I have tried debugging and it crashes somewhere between converting line 2 and 3. I am sorry but I cannot figure out exactly where but in a function either in adFaxCvt or AwFaxCvt file.  I have spend quite some time on this and tried changing several parameters and text etc. but the error seems to be quite stable e.g. should be easy to reproduce.
If somebody could fix this I would be VERY grateful.
thanks

**Comment by romankassebaum** [comment]
I have no idea how to fix the issue.
