### ISSUE TITLE
[ilink32 Error] Error: Unable to open file 'ADSELCOM.DFM'

### ISSUE THREAD

**Issue by 5age81** [TurboPack/AsyncPro#16]
I try to disable 'Link with runtime packages' , and added a ApdComPort1, but when i Build the project, the linker throw an error:
 [ilink32 Error] Error: Unable to open file 'ADSELCOM.DFM'

I have set the directory to the correct path, and if i compile and link WITH the runtime packages it work !
But i needed a application that can run WITHOUT the runtime packages...

I'm using the RAD Studio 10.4 Update 2 

Any suggestions ?
Thank you

Updated: i solved the issue , i just copied the file ADSELCOM.DFM into the directory of the project.... The linker was able to find the file and create an executable application WITHOUT the runtime packages...

Updated part 2: i solved by the regular way ... I missed a library Path... My fault ... No needed anymore to put the ADSELCOM.DFM file in the directory...

**Comment by romankassebaum** [comment]
I'm not a C++ specialist but from what you explained I think that a search path is missing.
