### ISSUE TITLE
VT100 Emulation Broken

### ISSUE THREAD

**Issue by AmateurCritic** [TurboPack/AsyncPro#16]
WIth XE7, the VT100 Emulator fails to decode the sequences. Is the ESC character, $1B, being eaten?
The same project with AsyncPro V3 and Delphi5 worked great.

**Comment by romankassebaum** [comment]
Do you have a demo app?

**Comment by AmateurCritic** [comment]
Roman,

Thanks for your prompt response.

Please find the demo programme attached, including a compiled windows 
32bit executable.

The VT100 input displays fine on TeraTerm. On the demo it seems to get 
the wrong characters; I can see some correct colour changes and GotoXY 
commands, but the rest is gibberish.
I think my original guess concerning the eaten ESC character is wrong. 
Maybe this is more to do with the Unicode abortion.


Best regards,

John

**Comment by sbridger** [comment]
Perhaps you would like to try a recent version of Realterm (www.i2cchip.com/realterm) and see if the terminal does what you expect.

It is currently compiled with XE2 - so it might be close enough for test purposes

**Comment by romankassebaum** [comment]
I'm sorry but I do not understand you. There seems to be nothing attached.

**Comment by AmateurCritic** [comment]
Roman,

The zipped project, VT100Demo.zip, was attached to the email I sent. I noticed that the resulting 
forum entry lacked it, but assumed that it was removed for your delectation.

I tried to add it to my post by the stated "drap & drop", but received the following error: "Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "

Perhaps you could send me an email address that I could send you the file directly.

**Comment by AmateurCritic** [comment]
Mr. Bridger,

Thank you for your offer, but I have used AsyncPro extensively in most of my projects; this is why I have stuck with Delphi5 for so long. This thread is about fixing a problem with AP, *not* with finding an alternative.
I can't believe how Embarcadero have screwed-up Delphi by redefining strings and chars as Unicode! Why should one have to perform major edits of hitherto functioning code?

**Comment by romankassebaum** [comment]
You can send me a PM. My address is
roman (at) kassebaum (dot) eu

**Comment by AmateurCritic** [comment]
Thank you Roman, you have fixed it. Well done and much faster than most commercial organisations.
[ File affected:  AsyncPro/source/ADTrmEmu.pas]
I'm now closing this issue.

**Comment by sbridger** [comment]
Hi AC, 
Could you give a test case for this problem, so I can check if I have the same problem?

My code lacks the offending cast, and you havn't given an example, so I can't really tell if this is a hidden bug or not for my users.

My code....
`      ExtTextOut(Canvas.Handle,
                 WorkRect.Left,
                 WorkRect.Top,
                 ETO_OPAQUE,
                 @WorkRect,
                 FDisplayStr,
                 PartTextLen,
                 @FCellWidths^);`

**Comment by AmateurCritic** [comment]
Mr. Bridger,
I explained above that I was unable to drap & drop, nor to attach a file via email.
I had to send the demo project directly to Herr Kassebaum.
Am I the only one to have difficulty in providing files?

**Comment by sbridger** [comment]
Hi AC, What I wanted was an ansi/VT100 command sequence that fails, and a descripttion of what it should do, so I can test Realterm and see if I have the same bug.

For example this is the ansi/VTW100 sequence I have tried, and it works.
`esc[5;5H`  does "move cursor to 5,5" 
 and this works OK in Realterm 3.0.0.29

**Comment by AmateurCritic** [comment]
Mr. Bridger,
The visual effect was that text written to the screen was garbled; the characterers displayed were *not* those sent. Please look at Herr Kassebaum's log, where the cast was to a pointer, instead of a string.
![Uploading VT100.jpg…]()

**Comment by sbridger** [comment]
Thanks, looks like my codec is OK then.

Wonder why Roman is bothering with the explicit typecast at all, as mine works without it?

**Comment by romankassebaum** [comment]
Otherwise there would be a warning.
