### ISSUE TITLE
Backspace Key (and ^H) sends 0x7F in all terminals

### ISSUE THREAD

**Issue by sbridger** [TurboPack/AsyncPro#17]
Is this actually a bug or is it something deliberate, for reasons I don't understand?

Backspace Key and ^H,  sends 0x7F in all terminals. 
In Ansi/VT100,term only, shift+backspace does send 0x08

https://sourceforge.net/p/realterm/bugs/64/

**Comment by romankassebaum** [comment]
I don't know realterm.

**Comment by sbridger** [comment]
This is an AdTerminal window, with plain or ansi/vt100 emulators.
I think it has always been this way. (ie not a recent regression) 
Which is why I wonder if it is not a bug, but something that makes sense, though I can't see why.

**Comment by romankassebaum** [comment]
Dear sbridger,

this is a bug tracker and not a discussion forum.

**Comment by sbridger** [comment]
OK, Well to my way of thinking this is a bug then: 
The backspace key should probably emit backspace.not del, and ^H should definitely be backspace.

I have been unable to get my head around the whole keyboard mapping arrangement in tp.
Is this happening because of the keymapping or is it in code?
Can we just make an alternative (correct) keymap, and leave the default the way it is?
