### ISSUE TITLE
C++Builder classic compiler does not like the argument name SType

### ISSUE THREAD

**Issue by weirdo12** [TurboPack/AsyncPro#18]
Errors from RAD Studio 11 - commenting out or deleting the argument name SType allows the code to compile. I have inserted the source from the .hpp's

[C++ Error] AwUser.hpp(264, 42):  expected ')'
[C++ Error] AwUser.hpp(264, 32):  to match this '('

	int __fastcall AddStatusTrigger(unsigned SType);

[C++ Error] AdPort.hpp(282, 61):  expected ')'
[C++ Error] AdPort.hpp(282, 41):  to match this '('

	System::Word __fastcall AddStatusTrigger(const System::Word SType);

**Comment by romankassebaum** [comment]
I could compile the packages. Could you please provide more details?

**Comment by weirdo12** [comment]
Okay, it must be something to do with the combination of 3rd Party controls I'm using. I'll create a project with just AsyncPro and then add them one at a time.

**Comment by weirdo12** [comment]
Roman, I have no idea why but the issue has gone away.
