### ISSUE TITLE
Terminal (keyboard emulator) swallows all shortcuts/hotkeys

### ISSUE THREAD

**Issue by sbridger** [TurboPack/AsyncPro#2]
It seems the terminal swallows all keystrokes when it has focus.
This results in the shortcuts/hotkeys for menu items not working.
Need for emulator to pass on unused keystrokes, or hook into keystroke parsing after the menus.
Doesn't seem to be a function of the emulator used.

**Comment by romankassebaum** [comment]
I'm sorry but I have no idea about what you are talking.

**Comment by sbridger** [comment]
I have made a sample here (XE2), there is a compiled exe so you can see what the problem is.
https://dl.dropboxusercontent.com/u/14839325/Hotkeys_Example_5May15.zip
 Ignore the global hotkeys buttons (these assign windows-wide hotkeys and handle them)

This app has main and popup menus. 
These menus have shortcut keys assigned (F6,F7,F10,F11, CtrlF10,CtrlF11)
When you press one of these shortcuts/hotkeys (eg F6), the label "MenuClick from" will change to show the name of the menuitem that sent the click eg (MIF6).
So, when you start the application you can press any of the hotkeys (F6,F7,F10,F11, CtrlF10,CtrlF11), and see that they are being processed.

Now click in the Terminal window with the mouse. When you press a hotkey, nothing happens - the Terminal is swallowing the hotkeys, before the menu processing can see them.
If you click back on the button "Bring Focus Back to Form (from Terminal)" , you will again be able to use the hotkeys.

Unfortunately having Terminal block the application wide shortcut/hotkeys rather makes them pointless...

**Comment by marcocantu** [comment]
While I never used that component I have the impression this is exactly as designed. If the terminal window has the focus, it receives all keyboard input. These components have been build a lot of time ago, all we are doing here is making them work with recent versions of Delphi, not really rework their architecture. Just Saying. they are open source projects, contributors are welcome to extend them.

**Comment by sbridger** [comment]
I know how old they are - I bought them new!

I'm not sure if they were intended to work that way but the manual implies to me that the application should still be able to process its shortcuts, when "WantAllKeys=false"
My app has some shortcuts in it, and they probably worked when I added them, but the changelog has hints that they became a problem by 2005, which might have been the jump to V2 using Delphi7. So it could be that the CN_KEYDOWN behaviour changed subtley in Delphi7.(or maybe they were alway buggy - after 15 years who knows?)

The solution may well be a delphi thing as the problem is actually: How do I stop a control/panel on the form from swallowing all the keystrokes BEFORE the menus on the form can see them can see them?
The ADTrmEMu only seems to have a single, simple routine hooking the CN_KEYDOWN message. 
So I'd expect that either there should be a call there to re-issue the unused keystrokes so the parent form can then see them, or there should be some way to make the terminal hook keydown after the menus have had at it.

----
It would be nice to be able to merge my own versions back into a maintained version again.
Sadly I find the code very convoluted and largely incomprehensible, due to the lack of comments. So when I hack something to get it to work, I am certain it is actually the wrong way to do it!
So, not sure if I would be doing anyone else any favours!

**Comment by sbridger** [comment]
Seems that use of CN_KEY?? message blocks the special keys reaching the menus.
WM_KEYDOWN lets ^T reach menus
WM_KEYDOWN lets F10 reach menus

Changed AdTrmEmu to use WM_Key??

```     
procedure CNKeyDown(var Msg : TWMKeyDown); message WM_KEYDOWN;   //sjb allows shortcuts (F10, ^T etc to reach menus)
procedure CNSysKeyDown(var Msg : TWMKeyDown); message WM_SYSKEYDOWN;

     //procedure CNKeyDown(var Msg : TWMKeyDown); message CN_KEYDOWN;
     //procedure CNSysKeyDown(var Msg : TWMKeyDown); message CN_SYSKEYDOWN;
```

Does look like a delphi bug to me: when Msg.result:=0, the F10 key is still making the main menubar appear pressed, and when Msg.result:=1 it doesn't. So the key is still getting back into delphi after the AdTrmEmu handler, but just not getting to the menus then.

Anyone know anymore about CN_KEYDOWN vs WM_KEYDOWN? (ie why this would be a bad idea )

**Comment by sbridger** [comment]
Well there is a problem with WM_KEYDOWN....
There are KeyDown and KeyPress procedures.
The KeyDown procedure is called from CNKeyDown.
The KeyPressed procedure is called from out of the blue.
When I set Msg.Result:=1 for WM_KEYDOWN, then keypressed operator still fires (wrong)
Using the CM_KEYDOWN, Msg:=1 supresses Keypress (correct)
I can't see anywhere that actually sets up the KeyPress to a message.

**Comment by sbridger** [comment]
Missing "IsMenuKey" in CNKeyDown
http://edn.embarcadero.com/article/38447  (from 2008)
Says that TWinControl.IsMenuKey should be called, but (ie XE2) this does not appear to be a in TWinControl, or mentioned in the help.

In 5.2.2 this shows a CKKEYDown handler. At the start, the call to IsMenuKey is what causes processing of all the shortcuts.
TAdTerminal is a descendent of TWinControl so should have this function.

**Comment by sbridger** [comment]
Finally got it working:
While WM_KEYDOWN handler made menus work, it broke the FKeyDown handler, so I had to revert to CNKEYDOWN.

* Add an IsMenu function. Unable to duplicate the TWinControl functionality as too many things are private, but can see menu attatched directly to AdTerminal. 
* Added system popup menu to AdTerminal popupmenu, so it can be seen
* WantAllKeys=true, otherwise all ordinary keys leak out to button shortcuts etc.


While I can get the parent form, I can't see the menu there to check it - private again.
Can't see why VCL is posting appmessge, so I don't
UpdateUI state didn't seem to be doing anything.
```
function TAdCustomTerminal.IsMenuKey(var Message: TWMKey): Boolean;
//var Form: TCustomForm;
begin
  Result := True;
  if not (csDesigning in ComponentState) then
  begin
      if Assigned(PopupMenu) and (PopupMenu.WindowHandle <> 0) and
       PopupMenu.IsShortCut(Message)
        then Exit;
//    Form := GetParentForm(Self);
//    if (Form <> nil) and Form.IsShortCut(Message) then Exit;
  end;
//  with Message do
//    if SendAppMessage(CM_APPKEYDOWN, CharCode, KeyData) <> 0 then Exit;
  Result := False;
end;
procedure TAdCustomTerminal.CNKeyDown(var Msg : TWMKeyDown);
var
  Shift  : TShiftState;
  EnhKey : boolean;
  Key    : word;
  NumLockState : TKeyboardState;
begin
  {if the left button is down (we're selecting) and the key is Escape,
   cancel the mode}
  UpdateUIState(Msg.CharCode);
  if IsMenuKey(Msg) then begin
      Msg.Result := 1;
      Exit;
  end;
......
```
