### ISSUE TITLE
Branch named HEAD causes issues

### ISSUE THREAD

**Issue by TomG17** [TurboPack/AsyncPro#20]
Could you delete the branch named HED, since it is considered an invalid name for a branch?

I came across this issue when mirroring this repo to a private GitLab instance.

**Comment by romankassebaum** [comment]
There is no branch head. There is only the remote origin/Head which is there in all GitHub projects. I think I should not delete this remote.

**Comment by TomG17** [comment]
On the GitHub website under [https://github.com/TurboPack/AsyncPro/branches](https://github.com/TurboPack/AsyncPro/branches) are 2 branches listed, one of them named "HEAD". 

None of the other TurboPack projects have such a branch. 

It would be great to have this somehow resolved, so that it is possible to automatically mirror this repository to my local git  server.

**Comment by romankassebaum** [comment]
Deleted.

**Comment by TomG17** [comment]
Thank you so much.
