### ISSUE TITLE
i download like a zip file but this AsyncProCR.bpl and others files MISSING in archive !!!!!

### ISSUE THREAD

**Issue by karadevnet** [TurboPack/AsyncPro#26]
i download like a zip file but this files MISSING in archive !!!!! i search all folders in archive but no never found it. can you upload them in archive ti can use it easly in package manager directly in rad studio ????

Delphi

    AsyncProDR.bpl (Delphi Runtime)
    AsyncProDD.bpl (Delphi Designtime)

C++Builder

    AsyncProCR.bpl (C++Builder Runtime)
    AsyncProCD.bpl (C++Builder Designtime)

**Comment by romankassebaum** [comment]
You have to compile the components yourself. Then the files are created.
