### ISSUE TITLE
package manager NOT_WORKING !!!

### ISSUE THREAD

**Issue by karadevnet** [TurboPack/AsyncPro#29]
what we do in this case when no pacake, no zip download working at all :(
[package_NOT_WORKING](https://user-images.githubusercontent.com/82239300/158659209-cc49a4cb-0c8a-4017-917a-288a7ffbdd17.jpg)

**Comment by TomG17** [comment]
Download the code from GitHub directly. Then manually install the package.

If you rely on this package, I recommend to have a local clone, so you can always use the code directly and are not depending on some network resource (in this case Getit server) that might not be available when you need it most.
