### ISSUE TITLE
Unsuccessful compilation on Delphi 10.1 Berlin

### ISSUE THREAD

**Issue by rafikaras** [TurboPack/AsyncPro#3]
I am migrating from Delphi 4 to Delphi 10.1 and having problems compiling
 some components belonging to TurboPower company (Async v5).
![async](https://user-images.githubusercontent.com/30107055/28109841-28af9cf6-66f9-11e7-8af0-971753c9df21.jpg)
Please see attached screen shot.

**Comment by romankassebaum** [comment]
Which version of AsyncPro are you using?

**Comment by rafikaras** [comment]
v5.00. Is it the suitable version for Delhi10.1 Berlin (update 2)?
Please have a look at the attached screenshot

**Comment by romankassebaum** [comment]
I just compiled the current with Delphi Berlin and there are no errors, warnings or hints. You are compiling an old version.

**Comment by rafikaras** [comment]
Ok tnx. tomorrow i will connect the machine to the web and try downloading
the latest version.

**Comment by rafikaras** [comment]
Hello again.
I unistalled the version which was installed on my machine (*V5.00!*).
Then I used the *GetIt *manager inside Delphi to install the *AsybcPro*!
Then again I received errors during compilation.
Please let me understand what should be the solution for this urgent issue.

*Attached a screenshot. Please have a look at it!*

**Comment by romankassebaum** [comment]
You should use the version here from GitHub not from GetIt. I'm sure that GetIt is out of date.
