### ISSUE TITLE
Number of handles increases after repeated attempts to open an unavailable COM port

### ISSUE THREAD

**Issue by michaelr1966** [TurboPack/AsyncPro#30]
We use a service that serves various serial scales. The COM interfaces are provided via the network via COM servers from W&T (Wiesemann & Theis GmbH). If, for example, this COM interface is not available in a test environment, the exception "Apro exception" occurs.

Rec=-995

![image](https://user-images.githubusercontent.com/103499059/162950106-acfbcd7f-c1f6-4a56-9239-860b46808851.png)

In my opinion, the reason are the 6 events (ComEvent, ReadyEvent, GeneralEvent, OutputEvent, SentEvent and OutFlushEvent) which are generated but not closed again in such a case.

![image](https://user-images.githubusercontent.com/103499059/162950493-aa54690a-1eea-4831-90a9-40c5dfcd0604.png)

**Comment by romankassebaum** [comment]
When do get the exception? How does the callstack look like?
Have you tried to catch the exception and to close the handle explicitly?

**Comment by michaelr1966** [comment]
Hello,


„When do get the exception?“

***@***.***

„ How does the callstack look like?“

***@***.***

„Have you tried to catch the exception and to close the handle explicitly?“

Yes, with the code above. The number of handles still increases by 6.



Best Regards

Michael Rieckhaus


Von: Roman Kassebaum ***@***.***>
Gesendet: Donnerstag, 14. April 2022 18:55
An: TurboPack/AsyncPro ***@***.***>
Cc: Michael Rieckhaus ***@***.***>; Author ***@***.***>
Betreff: Re: [TurboPack/AsyncPro] Number of handles increases after repeated attempts to open an unavailable COM port (Issue #30)


When do get the exception? How does the callstack look like?
Have you tried to catch the exception and to close the handle explicitly?

**Comment by michaelr1966** [comment]
_**„When do get the exception?“**_

By open the port. 

![image](https://user-images.githubusercontent.com/103499059/165033968-e5b0d129-9f4f-420e-bf25-9f0730191017.png)


**_„ How does the callstack look like?“_**
 
![image](https://user-images.githubusercontent.com/103499059/165034032-53602841-0fc4-46d2-8ac9-3b0a618df8fb.png)


_**„Have you tried to catch the exception and to close the handle explicitly?“**_

Yes, with the code above. The number of handles still increases by 6.

**Comment by michaelr1966** [comment]
**_"When do get the exception?"_**

By open the port.

![image](https://user-images.githubusercontent.com/103499059/165034618-072369ce-5cad-4440-b270-c70d4abd05b5.png)

**_"How does the callstack look like?"_**

![20220425-085055](https://user-images.githubusercontent.com/103499059/165035634-16cfb64c-cb85-4d66-aa16-dc711bbf3b82.jpg)

**_"Have you tried to catch the exception and to close the handle explicitly?"_**

Yes, with the code above. The number of handles still increases by 6.

**Comment by romankassebaum** [comment]
Can you find out in which line exactly in the Method InitPort the exception happens?

As a workaround could you please try the following code:

{code}
uses
  AdExcept, AwUser;

type
  TProtectedApdComPort = class(TApdComPort)
  end;
  TProtectedApdDispatcher = class(TApdBaseDispatcher)
  end;

procedure TForm1.Button1Click(Sender: TObject);
begin
  Button1.Enabled := False;
  try
    ApdComPort1.ComNumber := 2;
    ApdComPort1.Baud := 115200;
    ApdComPort1.DataBits := 8;
    ApdComPort1.StopBits := 1;
    ApdComPort1.Parity := pNone;
    ApdComPort1.HWFlowOptions := [];
    ApdComPort1.SWFlowOptions := swfNone;
    try
      ApdComPort1.Open := True;
    except
      on E: EAPDException do
      begin
        CloseHandle(TProtectedApdDispatcher(TProtectedApdComPort(ApdComPort1).FDispatcher).ComEvent);
        CloseHandle(TProtectedApdDispatcher(TProtectedApdComPort(ApdComPort1).FDispatcher).ReadyEvent);
        CloseHandle(TProtectedApdDispatcher(TProtectedApdComPort(ApdComPort1).FDispatcher).GeneralEvent);
        CloseHandle(TProtectedApdDispatcher(TProtectedApdComPort(ApdComPort1).FDispatcher).OutputEvent);
        CloseHandle(TProtectedApdDispatcher(TProtectedApdComPort(ApdComPort1).FDispatcher).SentEvent);
        CloseHandle(TProtectedApdDispatcher(TProtectedApdComPort(ApdComPort1).FDispatcher).OutFlushEvent);
      end;
    end;
  finally
    Button1.Enabled := True;
  end;
end;
{code}

**Comment by michaelr1966** [comment]
Here is the location were the value of -995 is set.

![image](https://user-images.githubusercontent.com/103499059/165457150-fde91235-4670-45d2-8b7a-cea16c93ffbc.png)


In the workaround code "TProtectedApdComPort(ApdComPort1).FDispatcher" is nil

![image](https://user-images.githubusercontent.com/103499059/165455495-0486a5e1-f417-4886-9c91-d5cd34d5e387.png)

**Comment by romankassebaum** [comment]
I hope I could fix the issue. Could you please try?

**Comment by michaelr1966** [comment]
I have tested it.
That solved the problem.
Thank you!
