### ISSUE TITLE
can't compile with delphi xe7, error missing imagelist.dcu

### ISSUE THREAD

**Issue by kempoxp** [TurboPack/AsyncPro#4]
[dcc32 Fatal Error] AdMdmDlg.pas(54): F1026 File not found: 'C:\delphi\async\packages\Delphi\ImageList.dcu'

help pls.

**Comment by romankassebaum** [comment]
This version is for Delphi Berlin. 

For XE7 I started https://github.com/TurboPack-XE7 but currently there is no AsyncPro.

**Comment by kempoxp** [comment]
thank you for the answer. i'll try this one on berlin

**Comment by mariodosreyx** [comment]
Sorry this link does not exist or is broken Is there any other way o getting imagelsit.pas/.dcu

**Comment by romankassebaum** [comment]
The XE7 branch does not exist any longer. You can try to compile the current version with XE7. The imagelist.pas unit does not exist under XE7, remove it from the uses clause.

You should try to move to Alexandria. HighDPI and ARM are not supported by XE7.
