### ISSUE TITLE
Any Chance to get AsyncPro working under RAD 10.2?

### ISSUE THREAD

**Issue by Sambo007** [TurboPack/AsyncPro#5]
Any Chance to get AsyncPro working under RAD 10.2?

Thanks.

**Comment by sbridger** [comment]
I have it running under 10.1

**Comment by pfintea** [comment]
I have it running under 10.2.0.
Do NOT download Async Pro from SourceForge because those version does not compile under Delphi XE.

**Comment by romankassebaum** [comment]
Currently we are only supporting 10.3.
