### ISSUE TITLE
Sending EOP issue

### ISSUE THREAD

**Issue by azapater** [TurboPack/AsyncPro#6]
Hi,

I'm experiencing issues sending faxes to some addressees. It just happen with a few specific ones. The sending process gets in a loop and it looks like it's not sending the EOP properly (the progress bar reaches the end though). Verifying what it has been actually sent in the recipient fax seems ok, so it's just an EOP process problem.

It is important to mention that this just happens in a Windows Server 2016 virtual machine. The same exe, using the same modem/fax in a regular server with Windows Server 2008 works fine on each sending process. 

Thanks

**Comment by romankassebaum** [comment]
I have no idea.
