### ISSUE TITLE
Any Chance to get AsyncPro working under Delphi XE7?

### ISSUE THREAD

**Issue by songorp** [TurboPack/AsyncPro#8]
Any Chance to get AsyncPro working under Delphi XE7?

**Comment by songorp** [comment]
I delete the Imagelist from uses then it can install the packed under XE7.

After i drop the TApdComport component at FMX Form and click create, i got a build error "Controls.dcu not found" from OoMisc. In VCL creating works without errors?

Please help

**Comment by romankassebaum** [comment]
We are only supporting 10.3.
