### ISSUE TITLE
ApdGSMPhone link error

### ISSUE THREAD

**Issue by timj-code** [TurboPack/AsyncPro#9]
Hi,
I'm testing sending sms using a 4G module.  Using C++ Builder 10.3 and in a VCL project.

The test project has only 2 TEdit and a TButton to send a sms, this code is like 
void __fastcall TForm2::Button1Click(TObject *Sender)
{
	ApdGSMPhone1->SMSAddress = Edit1->Text;
	ApdGSMPhone1->SMSMessage = Edit2->Text;
    ApdGSMPhone1->SendMessage();
}
At first it reports couldn't find "adgsm.h" and I manually pointed it to the AsyncPro-mast\source\AdGSM.hpp and added the folder to 'include directory', then I have and error:

ilink32 command line
  c:\program files (x86)\embarcadero\studio\20.0\bin\ilink32.exe -G8 -L.\Win32\Debug;"c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\debug";
  "C:\AsyncPro-master\source";"c:\program files (x86)\embarcadero\studio\20.0\lib\win32c\release";"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\win32c\release\psdk";C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP -j.\Win32\Debug;"c:\program files 
  (x86)\embarcadero\studio\20.0\lib\Win32\debug";"C:\AsyncPro-master\source";"c:\program files (x86)\embarcadero\studio\20.0\lib\win32c\release";
  "c:\program files (x86)\embarcadero\studio\20.0\lib\win32c\release\psdk";C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP -l.\Win32\Debug -v 
  -GA"C:\Users\wunei\AppData\Local\Temp\vfs8BF5.tmp"="C:\Users\wunei\Documents\Working\CppBuilder\sms_test\Unit2.dfm" -aa -V5.0 -Tpe c0w32w rtl.bpi 
  vcl.bpi AsyncProCR.bpi vclx.bpi memmgr.lib sysinit.obj .\Win32\Debug\Project1.obj .\Win32\Debug\Unit2.obj , .\Win32\Debug\Project1.exe , 
  .\Win32\Debug\Project1.map , import32.lib cp32mti.lib , , Project1.res 
**[ilink32 Error] Error: Unresolved external '__fastcall Adgsm::TApdCustomGSMPhone::SendMessageW()' referenced from C:\USERS\WUNEI\DOCUMENTS\WORKING\CPPBUILDER\SMS_TEST\WIN32\DEBUG\UNIT2.OBJ**
[ilink32 Error] Error: Unable to perform link

It says a SendMessageW() function not found. Could anybody help to figure out how to fix this?
Thanks

**Comment by romankassebaum** [comment]
I'm not a C++ expert. Maybe you should ask the C++ community.
